apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: paperless-admin
  namespace: paperless-ngx
spec:
  forceRegenerate: false
  fields:
  - fieldName: password
    encoding: base64
    length: "32"
